*WARNING: This contains SPOILERS*

* Gameplay

  It would be cool to have a passive storyline - for instance, if you want to, you could stop and listen to what people are talking about, or you could sneak past them / kill them / whatever. At the end of each Act, there could be cutscenes for critical storyline points.

  Every Hugh must arrive at the end goal simultaneously.

* Artwork

  In Act 1, every universe has the same tileset. However, the tileset in each universe will start diverging, starting with Act 2.

* Plot
** Act 1

  - Player finds/invents/discovers a device that allows him to experience multiple parallel universes simultaneously.
  - Continues solving puzzles, the world is hunky dory.
  - Accidentally opens a wormhole and let's a crazy creature through
 
** Act 2

  - To continue solving puzzles and improve the device, he has to kill bystanders occasionally.
  - Something involving going insane due to living in multiple universes simultaneously.
  - Player is searching for the creature, but has to kill on the way

** Act 3

  - The government comes after him, since he is killing people.

** Act 4

  - After defeating the government, he realizes that every universe he has touched has been getting destroyed. People live in horror.
  - Anarchy
  - At the end, he travels to an unknown dimension to live out the rest of his days, lest he completely destroy life for everyone.
  - The player should realize by the end how messed up he was - the gov wasn't the problem, the player was.

* Boss ideas

** Act 1

   Pan-dimensional creature that you must slay. Better yet: The only reason the creature is pan-dimensional is because of a wormhole you accidentally open (which is how he arrives in your universe). You can't close the wormhole until you defeat it, but then you have to hunt it down.

** Act 2
   
   TBD

** Act 3
   
   Government agents. Swarms of them, but they act differently in each universe.
   
** Act 4

   Creature comes back.

* Terminology
  
** Hugh

   The main character (subject to change)
   
** Universe

   What is displayed in each viewport.
   
** Act
   
   What is called "worlds" in the mario games. A group of levels. Each Act ends with a boss fight.

** D3vice

   The device (TBD) that let's Hugh interact with parallel universes.

* Development Notes
  
  We shall use the Tiled Map Editor! Thus, we will have a tile-based collision system.
  https://github.com/marshallward/TiledSharp
  https://github.com/Temeez/TiledSharp-MonoGame-Example
  http://doc.mapeditor.org/en/stable/manual/layers/#object-layers
  
  We could have an object layer to indicate positions of entities such as enemies, the player, etc. Maybe some switches and stuff.
  
  There could also be a "background" layer in each world, which is drawn, and cannot be interacted with.
  
  There should be several types of layers. ~universal_bg~, ~universal_fg~ for bg and fg among _all_ worlds. For parts of each world that differs, use the ~world0_bg~, ~world0_fg~, ~world1_fg~, etc.
  
  Each level can have an associated Lua script... but that will come in the future!
  
  I was looking at how MegaMan handled collisions and tiling, and we can totally do something similar.
